# Generated by Django 4.1.3 on 2022-11-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_created_alter_article_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Müəllif'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Qapaq Şəkli'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Dəyişdirilmə Tarixi'),
        ),
    ]
