# Generated by Django 4.1.3 on 2022-11-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
